config/routes.rb
Rails.application.routes.draw do
  resources :line_up_booms

end

app/models/line_up_boom.rb
class LineUpBoom < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/line_up_booms_controller.rb
class LineUpBoomsController < ApplicationController
  before_action :set_line_up_boom, only: [:show, :edit, :update, :destroy]

  # GET /line_up_booms
  # GET /line_up_booms.json
  def index
    @line_up_booms = LineUpBoom.all
  end

  # GET /line_up_booms/1
  # GET /line_up_booms/1.json
  def show
  end

  # GET /line_up_booms/new
  def new
    @line_up_boom = LineUpBoom.new
  end

  # GET /line_up_booms/1/edit
  def edit
  end

  # POST /line_up_booms
  # POST /line_up_booms.json
  def create
    @line_up_boom = LineUpBoom.new(line_up_boom_params)

    respond_to do |format|
      if @line_up_boom.save
        format.html { redirect_to @line_up_boom, notice: 'Line up boom was successfully created.' }
        format.json { render :show, status: :created, location: @line_up_boom }
      else
        format.html { render :new }
        format.json { render json: @line_up_boom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_up_booms/1
  # PATCH/PUT /line_up_booms/1.json
  def update
    respond_to do |format|
      if @line_up_boom.update(line_up_boom_params)
        format.html { redirect_to @line_up_boom, notice: 'Line up boom was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_up_boom }
      else
        format.html { render :edit }
        format.json { render json: @line_up_boom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_up_booms/1
  # DELETE /line_up_booms/1.json
  def destroy
    @line_up_boom.destroy
    respond_to do |format|
      format.html { redirect_to line_up_booms_url, notice: 'Line up boom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_up_boom
      @line_up_boom = LineUpBoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_up_boom_params
      params.require(:line_up_boom).permit(:DjName, :SetTime, :MusicStyle)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/line_up_booms_helper.rb
module LineUpBoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyNewApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/line_up_booms/_form.html.erb
<%= form_for(@line_up_boom) do |f| %>
  <% if @line_up_boom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_up_boom.errors.count, "error") %> prohibited this line_up_boom from being saved:</h2>

      <ul>
      <% @line_up_boom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :DjName %><br>
    <%= f.text_area :DjName %>
  </div>
  <div class="field">
    <%= f.label :SetTime %><br>
    <%= f.date_select :SetTime %>
  </div>
  <div class="field">
    <%= f.label :MusicStyle %><br>
    <%= f.text_area :MusicStyle %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_up_booms/edit.html.erb
<h1>Editing line_up_boom</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_up_boom %> |
<%= link_to 'Back', line_up_booms_path %>

app/views/line_up_booms/index.html.erb
<h1>Listing line_up_booms</h1>

<table>
  <thead>
    <tr>
      <th>Djname</th>
      <th>Settime</th>
      <th>Musicstyle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_up_booms.each do |line_up_boom| %>
      <tr>
        <td><%= line_up_boom.DjName %></td>
        <td><%= line_up_boom.SetTime %></td>
        <td><%= line_up_boom.MusicStyle %></td>
        <td><%= link_to 'Show', line_up_boom %></td>
        <td><%= link_to 'Edit', edit_line_up_boom_path(line_up_boom) %></td>
        <td><%= link_to 'Destroy', line_up_boom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line up boom', new_line_up_boom_path %>

app/views/line_up_booms/new.html.erb
<h1>New line_up_boom</h1>

<%= render 'form' %>

<%= link_to 'Back', line_up_booms_path %>

app/views/line_up_booms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Djname:</strong>
  <%= @line_up_boom.DjName %>
</p>

<p>
  <strong>Settime:</strong>
  <%= @line_up_boom.SetTime %>
</p>

<p>
  <strong>Musicstyle:</strong>
  <%= @line_up_boom.MusicStyle %>
</p>

<%= link_to 'Edit', edit_line_up_boom_path(@line_up_boom) %> |
<%= link_to 'Back', line_up_booms_path %>